paths:
  /produto:
    get:
      tags:
        - Produto
      summary: Retrieve Product
      security: 
             - githubAuth: ['read'] # Oauth 2
      produces:
        - application/json
      responses:
        200:
          description: Success Message
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/produto"
        "401":
          description: Unauthorized
    post:
      tags:
        - Produto
      summary: Create Produto
      security:
          - githubAuth: ['write'] # Oauth 2
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/produtoEx"
          application/xml:
            schema:
              $ref: "#/definitions/produtoEx"
      responses:
        "200":
          description: Create a Product model instance
          content:
            application/json:
              schema:
                $ref: "#/definitions/produto"
            application/xml:
              schema:
                $ref: "#/definitions/produto"
        "401":
          description: Unauthorized
  /produto/{id}:
    get:
      tags:
        - Produto
      summary: Retrieve Produto
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            minimum: 1
            type: integer
            format: int64
          examples:
            one:
              summary: Retrieve Product id 1
              value: 1
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/definitions/produto"
        "400":
          description: Bad request
        "404":
          description: id not found
    put:
      tags:
        - Produto
      summary: Update Product
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            minimum: 1
            type: integer
            format: int64
          examples:
            one:
              summary: Update Product id 1
              value: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/produtoEx"
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                description: Product updated success
                $ref: "#/definitions/produto"
        "400":
          description: Bad request
        "404":
          description: id not found
    delete:
      tags:
        - Produto
      summary: Delete Product
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
          examples:
            one:
              summary: Delete Product id 1
              value: 1
      responses:
        "204":
          description: No content
        "404":
          description: id not found
definitions:
  produto:
    type: object
    properties:
      id:
        type: integer
      nome:
        type: string
      preco:
        type: string
      quantidade:
        type: string
  produtoEx:
    type: object
    properties:
      nome:
        type: string
      preco:
        type: string
      quantidade:
        type: string
