openapi: 3.0.3
info:
  title: E-commerce API
  version: 1.0.0
servers:
- url: http://localhost:3001/docs/
paths:
  /usuarios:
    post:
      summary: Criar um novo usuario
      operationId: usuariosPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
        required: true
      responses:
        "201":
          description: Usuario criado com sucesso
        "400":
          description: Erro ao criar o Usuario
      x-swagger-router-controller: Default
  /usuarios/{id}:
    get:
      summary: Obter um usuário pelo ID
      operationId: usuariosIdGET
      parameters:
      - name: id
        in: path
        description: ID do usuário a ser obtido
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Usuário obtido com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        "404":
          description: Usuário não encontrado
      x-swagger-router-controller: Default
    delete:
      summary: Excluir um usuário pelo ID
      operationId: usuariosIdDELETE
      parameters:
      - name: id
        in: path
        description: ID do usuário a ser excluído
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: Usuário excluído com sucesso
        "404":
          description: Usuário não encontrado
      x-swagger-router-controller: Default
  /produtos:
    get:
      summary: Obter a lista de produtos
      operationId: produtosGET
      responses:
        "200":
          description: Lista de produtos obtida com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produto'
                x-content-type: application/json
      x-swagger-router-controller: Default
  /pedidos:
    post:
      summary: Criar um novo pedido
      operationId: pedidosPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pedido'
        required: true
      responses:
        "201":
          description: Pedido criado com sucesso
        "400":
          description: Erro ao criar o pedido
      x-swagger-router-controller: Default
  /pedidos/{id}:
    delete:
      summary: Deletar um usuário pelo ID
      operationId: pedidosIdDELETE
      parameters:
      - name: id
        in: path
        description: ID do usuário a ser deletado
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: Usuário deletado com sucesso
        "404":
          description: Usuário não encontrado
      x-swagger-router-controller: Default
  /categorias:
    post:
      responses:
        '200':
          description: Resposta bem-sucedida
          content:
            application/json:
              schema:
                type: object
                properties:
                  nome:
                    type: string 
                required:
                  - nome
                      
components:
  schemas:
    Usuario:
      type: object
      properties:
        nome:
          type: string
        email:
          type: string
        senha:
          type: string
      example:
        senha: senha
        nome: nome
        email: email
    Produto:
      type: object
      properties:
        nome:
          type: string
        descricao:
          type: string
        preco:
          type: number
        quantidade:
          type: integer
        imagem:
          type: string
      example:
        preco: 0.80082819046101150206595775671303272247314453125
        imagem: imagem
        nome: nome
        quantidade: 6
        descricao: descricao
    Pedido:
      type: object
      properties:
        idUsuario:
          type: integer
        produtos:
          type: array
          items:
            $ref: '#/components/schemas/Pedido_produtos'
    Pedido_produtos:
      type: object
      properties:
        idProduto:
          type: integer
        quantidade:
          type: integer
    Categoria:
      type: object
      properties:
        nome:
          type: string
      example:
        nome: nome
       
       

      
 